## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function

## makeCacheMatrix function generates a matrix of variable size following the addition of number of rows and columns to the function

makeCacheMatrix <- function(x = matrix()) {
 z <- NULL
  set <- function(y){
    x <<-y
    z <<- NULL
}
         get <- function() {x}
  setInverse <- function(inverse) {z <<- inverse}
  getInverse <- function() {z}
  list(set = set, get = get, setInverse = setInverse, getInverse = getInverse)
}


## Write a short comment describing this function

## cacheSolve function --> creates the inverse of the matrix which was previously generated by "makeCacheMatrix" function
## If the inverse of the matrix has already been calculated then "getting cached data" message will appear below with the inverse of the original matrix
cacheSolve <- function(x, ...) {
  z <- x$getInverse()
  if (!is.null(z)){
    message("getting cached data")
    return(z)
  }
  mat <- x$get()
  z <- solve(mat, ...)
  x$setInverse(z)
  z
}  
  ## Return a matrix that is the inverse of 'x'
